# generated by datamodel-codegen:
#   filename:  2026-02-19_4a8d9317_daily_hr.json
#   timestamp: 2026-02-28T00:36:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class HeartRateValueDescriptor(BaseModel):
    key: str
    index: int


class HeartRate(BaseModel):
    userProfilePK: int
    calendarDate: str
    startTimestampGMT: str
    endTimestampGMT: str
    startTimestampLocal: str
    endTimestampLocal: str
    maxHeartRate: int
    minHeartRate: int
    restingHeartRate: int
    lastSevenDaysAvgRestingHeartRate: int
    heartRateValueDescriptors: list[HeartRateValueDescriptor]
    heartRateValues: list[list[int | None]]
