# generated by datamodel-codegen:
#   filename:  2026-02-19_4a8d9317_daily_sleep_data.json
#   timestamp: 2026-02-23T01:14:55+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel
from pydantic.functional_validators import field_validator


class TotalDuration(BaseModel):
    qualifierKey: str
    optimalStart: float
    optimalEnd: float


class Stress(BaseModel):
    qualifierKey: str
    optimalStart: float
    optimalEnd: float


class AwakeCount(BaseModel):
    qualifierKey: str
    optimalStart: float
    optimalEnd: float


class Overall(BaseModel):
    value: int
    qualifierKey: str


class RemPercentage(BaseModel):
    value: int
    qualifierKey: str
    optimalStart: float
    optimalEnd: float
    idealStartInSeconds: float
    idealEndInSeconds: float


class Restlessness(BaseModel):
    qualifierKey: str
    optimalStart: float
    optimalEnd: float


class LightPercentage(BaseModel):
    value: int
    qualifierKey: str
    optimalStart: float
    optimalEnd: float
    idealStartInSeconds: float
    idealEndInSeconds: float


class DeepPercentage(BaseModel):
    value: int
    qualifierKey: str
    optimalStart: float
    optimalEnd: float
    idealStartInSeconds: float
    idealEndInSeconds: float


class SleepScores(BaseModel):
    totalDuration: TotalDuration
    stress: Stress
    awakeCount: AwakeCount
    overall: Overall
    remPercentage: RemPercentage
    restlessness: Restlessness
    lightPercentage: LightPercentage
    deepPercentage: DeepPercentage


class SleepNeed(BaseModel):
    userProfilePk: int
    calendarDate: str
    deviceId: int
    timestampGmt: str
    baseline: int
    actual: int
    feedback: str
    trainingFeedback: str
    sleepHistoryAdjustment: str
    hrvAdjustment: str
    napAdjustment: str
    displayedForTheDay: bool
    preferredActivityTracker: bool


class NextSleepNeed(BaseModel):
    userProfilePk: int
    calendarDate: str
    deviceId: int
    timestampGmt: str
    baseline: int
    actual: int
    feedback: str
    trainingFeedback: str
    sleepHistoryAdjustment: str
    hrvAdjustment: str
    napAdjustment: str
    displayedForTheDay: bool
    preferredActivityTracker: bool


class DailySleepDTO(BaseModel):
    id: int
    userProfilePK: int
    calendarDate: str
    sleepTimeSeconds: int
    napTimeSeconds: int
    sleepWindowConfirmed: bool
    sleepWindowConfirmationType: str
    sleepStartTimestampGMT: int
    sleepEndTimestampGMT: int
    sleepStartTimestampLocal: int
    sleepEndTimestampLocal: int
    autoSleepStartTimestampGMT: None
    autoSleepEndTimestampGMT: None
    sleepQualityTypePK: None
    sleepResultTypePK: None
    unmeasurableSleepSeconds: int
    deepSleepSeconds: int
    lightSleepSeconds: int
    remSleepSeconds: int
    awakeSleepSeconds: int
    deviceRemCapable: bool
    retro: bool
    sleepFromDevice: bool
    averageSpO2Value: float
    lowestSpO2Value: int
    highestSpO2Value: int
    averageSpO2HRSleep: float
    averageRespirationValue: float
    lowestRespirationValue: float
    highestRespirationValue: float
    awakeCount: int
    avgSleepStress: float
    ageGroup: str
    avgHeartRate: float
    sleepScoreFeedback: str
    sleepScoreInsight: str
    sleepScorePersonalizedInsight: str
    sleepScores: SleepScores
    sleepVersion: int
    sleepNeed: SleepNeed
    nextSleepNeed: NextSleepNeed


class SleepMovementItem(BaseModel):
    startGMT: str
    endGMT: str
    activityLevel: float


STAGE_NAMES = {
    -1.0: "unmeasurable",
    0.0: "deep",
    1.0: "light",
    2.0: "rem",
    3.0: "awake",
}


class SleepLevel(BaseModel):
    startGMT: datetime
    endGMT: datetime
    activityLevel: str

    @field_validator("activityLevel", mode="before")
    @classmethod
    def map_activity_level(cls, v):
        return STAGE_NAMES.get(float(v), v)


class SleepRestlessMoment(BaseModel):
    value: int
    startGMT: int


class WellnessSpO2SleepSummaryDTO(BaseModel):
    userProfilePk: int
    deviceId: int
    sleepMeasurementStartGMT: str
    sleepMeasurementEndGMT: str
    alertThresholdValue: None
    numberOfEventsBelowThreshold: None
    durationOfEventsBelowThreshold: None
    averageSPO2: float
    averageSpO2HR: float
    lowestSPO2: int


class WellnessEpochSPO2DataDTOListItem(BaseModel):
    userProfilePK: int
    epochTimestamp: str
    deviceId: int
    calendarDate: str
    epochDuration: int
    spo2Reading: int
    readingConfidence: int


class WellnessEpochRespirationDataDTOListItem(BaseModel):
    startTimeGMT: int
    respirationValue: float


class WellnessEpochRespirationAveragesListItem(BaseModel):
    epochEndTimestampGmt: int
    respirationAverageValue: float
    respirationHighValue: float | None
    respirationLowValue: float | None


class SleepHeartRateItem(BaseModel):
    value: int
    startGMT: int


class SleepStres(BaseModel):
    value: int
    startGMT: int


class SleepBodyBatteryItem(BaseModel):
    value: int
    startGMT: int


class HrvDatum(BaseModel):
    value: float
    startGMT: int


class Sleep(BaseModel):
    dailySleepDTO: DailySleepDTO
    sleepMovement: list[SleepMovementItem]
    remSleepData: bool
    sleepLevels: list[SleepLevel]
    sleepRestlessMoments: list[SleepRestlessMoment]
    restlessMomentsCount: int
    wellnessSpO2SleepSummaryDTO: WellnessSpO2SleepSummaryDTO
    wellnessEpochSPO2DataDTOList: list[WellnessEpochSPO2DataDTOListItem]
    wellnessEpochRespirationDataDTOList: list[WellnessEpochRespirationDataDTOListItem]
    wellnessEpochRespirationAveragesList: list[WellnessEpochRespirationAveragesListItem]
    respirationVersion: int
    sleepHeartRate: list[SleepHeartRateItem]
    sleepStress: list[SleepStres]
    sleepBodyBattery: list[SleepBodyBatteryItem]
    skinTempDataExists: bool
    hrvData: list[HrvDatum]
    avgOvernightHrv: float
    hrvStatus: str
    bodyBatteryChange: int
    restingHeartRate: int
